- name: restart docker
  service: name=docker enabled=yes state=restarted

# Not needed for hypriot-1.0.0 anymore
# - name: disable cluster-lab
#  service: name=cluster-lab enabled=false state=stopped
