etcd:
  port: 2379
network:
  service_subnet: 10.200.100.0/24
  pod_subnet: 10.1.0.0/16
version:
  kubernetes: 1.2.0
images:
  sky_dns: gcr.io/google_containers/skydns-arm:2015-12-13
  exechealthz: gcr.io/google_containers/exechealthz-arm:1.1
  kube2sky: gcr.io/google_containers/kube2sky-arm:1.11
  etcd: gcr.io/google_containers/etcd-arm:2.2.1
dns:
  service_ip: 10.200.100.10
  domain: cluster.local
