- name: Ensure that target directory /etc/docker exists
  file: path=/etc/docker state=directory recurse=false

- name: Add docker_init.sh for waiting on flannel to startup
  template: src=docker_init.sh dest=/etc/docker/docker_init.sh mode=0755

- name: Remove docker.service.d/*
  file: path=/etc/systemd/system/docker.service.d/overlay.conf state=absent

- name: Install own docker service
  template: src=docker.service dest=/etc/systemd/system/docker.service owner=root group=root mode=0644
  register: result
  notify:
    - restart docker
#    - disable cluster-lab

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed
